### ISSUE TITLE
Faulty Makefile?

### ISSUE THREAD

**Issue by cpwardell** [tobiasrausch/delly#16]
I pulled the latest version today, but it won't build from source.

I think the issue is that bootstrap.sh is listed in the Makefile but doesn't seem to exist.

**Comment by tobiasrausch** [comment]
Did you use the recursive checkout?

git clone --recursive https://github.com/tobiasrausch/delly.git

If you have checked out a zip file or without --recursive you can still do
the below (in the delly folder):

git submodule update --init --recursive


Does this work?

-Tobias

**Comment by cpwardell** [comment]
Forgive me, you are of course correct.  I hope 2015 brings you more uses that check the documentation properly.
