### ISSUE TITLE
requiring very large mem for INS

### ISSUE THREAD

**Issue by zd1** [tobiasrausch/delly#17]
Dear Delly Developers, 

I've been trying to use your tool to call variants. It works well for DEL DUP INV and TRA. However, I run into problems when I do INS. It consumes more than 64G memory. Is it expected? I am running it as below 

.src/delly -t ${sv} \
-o ${out} \
-g ${ref} \
-x ${exclude} \
${normal1} \
${normal2} \
${normal3} \
${normal4} \
${tumour}

Thanks very much, 
Zhihao

**Comment by tobiasrausch** [comment]
Hi Zhihao,

Insertions are not yet supported. Sorry, I should have deactivated -t INS

-Tobias
