### ISSUE TITLE
Delly install

### ISSUE THREAD

**Issue by yosr1977** [tobiasrausch/delly#18]
I'm trying to install delly and I keep having this error 

g++ -isystem /Users/julieballard/Downloads/delly/delly/src/modular-boost -isystem /Users/julieballard/Downloads/delly/delly/src/bamtools/include -isystem /Users/julieballard/Downloads/delly/delly/src/htslib/htslib -pedantic -W -Wall -Wno-unknown-pragmas -DNOPENMP -O9 -DNDEBUG src/delly.cpp -o src/delly -L/Users/julieballard/Downloads/delly/delly/src/modular-boost/stage/lib -lboost_iostreams -lboost_filesystem -lboost_system -lboost_program_options -lboost_date_time -L/Users/julieballard/Downloads/delly/delly/src/bamtools/lib -lbamtools -lz -Wl,-rpath,/Users/julieballard/Downloads/delly/delly/src/bamtools/lib,-rpath,/Users/julieballard/Downloads/delly/delly/src/modular-boost/stage/lib
error: invalid value '9' in '-O9'
make: *** [src/delly] Error 1

any clue?
thanks
yosr

**Comment by tobiasrausch** [comment]
Hi Yosr,

Looks like your compiler doesn't support higher optimization levels (probably OS X?). Just search for '-O9' in the Makefile and change it to '-O3'. This should work.

-Tobias

**Comment by yosr1977** [comment]
thank you !
yosr

**Comment by yosr1977** [comment]
Hi Tobias, 
I replaced 9 by 3 and I was able to run delly using the provided test data, but with my own data I'm having the following error message 
libc++abi.dylib: terminate called throwing an exception
Abort trap: 6
Any suggestions to fix that ?
below the command line I used
$ /Users/Yosr/delly/src/delly -t TRA  -x /Users/Yosr/delly/excludeTemplates/human.hg19.excl.tsv -o /Users//Yosr/VAlidation/AEFYV_Accuracy\ Run\ \#2/bam/AA1173_delly_TRA.vcf -g /Users//Yosr/Refrence_Genome/human_g1k_v37_decoy.fasta /Users//Yosr/VAlidation/AEFYV_Accuracy\ Run\ \#2/bam/AA1173.merged.sorted.bam

**Comment by yosr1977** [comment]
Hi Tobias, I fixed this issue,
thanks
y

**Comment by yosr1977** [comment]
Hi Tobias, 
I tried Delly on several samples  and it's always showing this :+1: 
____________________________________________________________
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
No structural variants found!
Done.
____________________________________________________________

Most of the samples I'm testing have SV and INDELs that I can see on IGV but I cant see any with Delly. I'm using bam files generated from target paired end sequencing and I was wondering if this can be a problem related to that and if Delly works only for whole genome seq or for some specific insert size ranges?
thank you for your help !
yosr

**Comment by tobiasrausch** [comment]
Hi Yosr,

Can you see them in IGV with abnormal paired-ends spanning the SV? For targeted sequencing you might have a very small insert size distribution with overlapping reads then paired-end methods such as Delly have zero power to detect SVs. You can check your insert size distribution using a tool included in Delly: https://github.com/tobiasrausch/delly/wiki/Alignment-Statistics

-Tobias

**Comment by yosr1977** [comment]
Hi Tobias,
I'm pasting the results from the stat tool, let me know what do you think,

Statistics.txt--------------------------------------------------------------------------------------------
SAM file: /Users/julieballard/Documents/Yosr/VAlidation/AEFYV_AccuracyRun#2/bam/AA1173.merged.sorted.bam

Reference information 
1 (249250621bp); 2 (243199373bp); 3 (198022430bp); 4 (191154276bp); 5 (180915260bp); 6 (171115067bp); 7 (159138663bp); 8 (146364022bp); 9 (141213431bp); 10 (135534747bp); 11 (135006516bp); 12 (133851895bp); 13 (115169878bp); 14 (107349540bp); 15 (102531392bp); 16 (90354753bp); 17 (81195210bp); 18 (78077248bp); 19 (59128983bp); 20 (63025520bp); 21 (48129895bp); 22 (51304566bp); X (155270560bp); Y (59373566bp); MT (16569bp); GL000207.1 (4262bp); GL000226.1 (15008bp); GL000229.1 (19913bp); GL000231.1 (27386bp); GL000210.1 (27682bp); GL000239.1 (33824bp); GL000235.1 (34474bp); GL000201.1 (36148bp); GL000247.1 (36422bp); GL000245.1 (36651bp); GL000197.1 (37175bp); GL000203.1 (37498bp); GL000246.1 (38154bp); GL000249.1 (38502bp); GL000196.1 (38914bp); GL000248.1 (39786bp); GL000244.1 (39929bp); GL000238.1 (39939bp); GL000202.1 (40103bp); GL000234.1 (40531bp); GL000232.1 (40652bp); GL000206.1 (41001bp); GL000240.1 (41933bp); GL000236.1 (41934bp); GL000241.1 (42152bp); GL000243.1 (43341bp); GL000242.1 (43523bp); GL000230.1 (43691bp); GL000237.1 (45867bp); GL000233.1 (45941bp); GL000204.1 (81310bp); GL000198.1 (90085bp); GL000208.1 (92689bp); GL000191.1 (106433bp); GL000227.1 (128374bp); GL000228.1 (129120bp); GL000214.1 (137718bp); GL000221.1 (155397bp); GL000209.1 (159169bp); GL000218.1 (161147bp); GL000220.1 (161802bp); GL000213.1 (164239bp); GL000211.1 (166566bp); GL000199.1 (169874bp); GL000217.1 (172149bp); GL000216.1 (172294bp); GL000215.1 (172545bp); GL000205.1 (174588bp); GL000219.1 (179198bp); GL000224.1 (179693bp); GL000223.1 (180455bp); GL000195.1 (182896bp); GL000212.1 (186858bp); GL000222.1 (186861bp); GL000200.1 (187035bp); GL000193.1 (189789bp); GL000194.1 (191469bp); GL000225.1 (211173bp); GL000192.1 (547496bp); NC_007605 (171823bp); hs37d5 (35477943bp); 
Haploid genome length: 3137454505
Diploid genome length: 6274909010

Single-end statistics
Total number of reads: 984578
Number of mapped reads: 967067
Number of mapped reads (percentage): 98.2215%
Number of unmapped reads: 17511
Number of unmapped reads (percentage): 1.77853%
Total number of read 1: 492289
Number of mapped reads 1: 487466
Number of mapped reads 1 (percentage): 99.0203%
Number of unmapped reads 1: 4823
Number of unmapped reads 1 (percentage): 0.979709%
Total number of read 2: 492289
Number of mapped reads 2: 479601
Number of mapped reads 2 (percentage): 97.4227%
Number of unmapped reads 2: 12688
Number of unmapped reads 2 (percentage): 2.57735%

Mapped read statistics (967067 reads)
Minimum read length: 25
Mean read length: 172
Maximum read length: 239
Haploid sequencing coverage: 0.0531438
Diploid sequencing coverage: 0.0265719

Paired-end statistics
Total number of reads paired in sequencing: 984578
Total number of reads where both reads of a pair mapped: 956682
Total number of reads where both reads of a pair mapped (percentage): 97.1667%
Total number of reads where both reads of a pair mapped onto the same chromosome: 940396
Total number of reads where both reads of a pair mapped onto the same chromosome (percentage): 95.5126%
Total number of non-redundant reads paired in sequencing: 875088
Total number of non-redundant reads paired in sequencing (percentage): 88.8795%
Total number of non-redundant reads paired in sequencing and mapped to same chromosome: 858880
Total number of non-redundant reads paired in sequencing and mapped to same chromosome (percentage): 87.2333%

Insert size statistics of all paired reads mapped onto the same chromosome (940396 reads, 470198 pairs)
Insert size (lower quartile): 117
Insert size (median): 206
Insert size (upper quartile): 315
Haploid insert coverage: 0.0308724
Diploid insert coverage: 0.0154362

Strand specific orientations
FF+ (0): 121
FF- (1): 136
FR+ (2): 89392
FR- (3): 146851
RF+ (4): 96899
RF- (5): 136596
RR+ (6): 94
RR- (7): 109

Strand independent orientations
F+ (0): 215
F- (1): 245
R+ (2): 186291
R- (3): 283447

inserts.txt-----------------------------------------------------------------------------------------------
Size	Count	Orientation
0	0	F+
0	0	F-
0	0	R+
0	0	R-
5	0	F+
5	0	F-
5	0	R+
5	0	R-
10	0	F+
10	0	F-
10	0	R+
10	0	R-
15	0	F+
15	0	F-
15	0	R+
15	0	R-
20	0	F+
20	0	F-
20	4	R+
20	0	R-
25	0	F+
25	0	F-
25	17	R+
25	0	R-
30	0	F+
30	0	F-
30	25	R+
30	13	R-
35	0	F+
35	0	F-
35	18	R+
35	3775	R-
40	0	F+
40	0	F-
40	27	R+
40	6714	R-
45	0	F+
45	0	F-
45	56	R+
45	7059	R-
50	0	F+
50	0	F-
50	58	R+
50	6967	R-
55	0	F+
55	0	F-
55	39	R+
55	7269	R-
60	0	F+
60	0	F-
60	53	R+
60	7297	R-
65	0	F+
65	0	F-
65	71	R+
65	7555	R-
70	0	F+
70	0	F-
70	78	R+
70	7461	R-
75	0	F+
75	0	F-
75	88	R+
75	7440	R-
80	0	F+
80	0	F-
80	82	R+
80	7597	R-
85	0	F+
85	0	F-
85	99	R+
85	7607	R-
90	0	F+
90	0	F-
90	62	R+
90	7405	R-
95	0	F+
95	0	F-
95	87	R+
95	7367	R-
100	0	F+
100	0	F-
100	80	R+
100	7236	R-
105	0	F+
105	0	F-
105	69	R+
105	7188	R-
110	0	F+
110	0	F-
110	104	R+
110	7033	R-
115	0	F+
115	0	F-
115	91	R+
115	6937	R-
120	0	F+
120	0	F-
120	108	R+
120	7048	R-
125	0	F+
125	0	F-
125	93	R+
125	6795	R-
130	0	F+
130	0	F-
130	127	R+
130	6749	R-
135	0	F+
135	0	F-
135	120	R+
135	6634	R-
140	0	F+
140	0	F-
140	118	R+
140	6483	R-
145	0	F+
145	0	F-
145	144	R+
145	6434	R-
150	0	F+
150	0	F-
150	139	R+
150	6286	R-
155	0	F+
155	0	F-
155	145	R+
155	6317	R-
160	0	F+
160	0	F-
160	149	R+
160	6152	R-
165	0	F+
165	0	F-
165	158	R+
165	6002	R-
170	0	F+
170	0	F-
170	155	R+
170	5959	R-
175	0	F+
175	0	F-
175	163	R+
175	5731	R-
180	0	F+
180	0	F-
180	133	R+
180	5686	R-
185	0	F+
185	0	F-
185	163	R+
185	5675	R-
190	0	F+
190	0	F-
190	159	R+
190	6292	R-
195	0	F+
195	0	F-
195	176	R+
195	7344	R-
200	0	F+
200	0	F-
200	193	R+
200	7514	R-
205	0	F+
205	0	F-
205	220	R+
205	7465	R-
210	0	F+
210	0	F-
210	328	R+
210	7522	R-
215	0	F+
215	0	F-
215	2061	R+
215	9809	R-
220	0	F+
220	0	F-
220	2558	R+
220	9598	R-
225	0	F+
225	0	F-
225	2557	R+
225	5348	R-
230	1	F+
230	0	F-
230	2624	R+
230	459	R-
235	0	F+
235	0	F-
235	3118	R+
235	306	R-
240	0	F+
240	0	F-
240	4452	R+
240	350	R-
245	0	F+
245	0	F-
245	4296	R+
245	412	R-
250	0	F+
250	0	F-
250	4305	R+
250	447	R-
255	0	F+
255	0	F-
255	4137	R+
255	454	R-
260	0	F+
260	0	F-
260	4117	R+
260	559	R-
265	0	F+
265	0	F-
265	3979	R+
265	476	R-
270	0	F+
270	0	F-
270	3777	R+
270	380	R-
275	0	F+
275	0	F-
275	3946	R+
275	537	R-
280	0	F+
280	0	F-
280	3822	R+
280	584	R-
285	0	F+
285	0	F-
285	3623	R+
285	636	R-
290	0	F+
290	0	F-
290	3585	R+
290	766	R-
295	0	F+
295	0	F-
295	3481	R+
295	782	R-
300	0	F+
300	0	F-
300	3498	R+
300	649	R-
305	0	F+
305	0	F-
305	3293	R+
305	471	R-
310	0	F+
310	0	F-
310	3323	R+
310	428	R-
315	0	F+
315	0	F-
315	3267	R+
315	405	R-
320	0	F+
320	0	F-
320	3177	R+
320	367	R-
325	0	F+
325	0	F-
325	3064	R+
325	369	R-
330	0	F+
330	0	F-
330	3006	R+
330	373	R-
335	0	F+
335	0	F-
335	2845	R+
335	341	R-
340	0	F+
340	0	F-
340	2857	R+
340	373	R-
345	0	F+
345	0	F-
345	2780	R+
345	325	R-
350	0	F+
350	0	F-
350	2749	R+
350	284	R-
355	0	F+
355	0	F-
355	2654	R+
355	317	R-
360	0	F+
360	0	F-
360	2569	R+
360	308	R-
365	0	F+
365	0	F-
365	2524	R+
365	304	R-
370	0	F+
370	0	F-
370	2446	R+
370	281	R-
375	0	F+
375	0	F-
375	2348	R+
375	273	R-
380	0	F+
380	0	F-
380	2269	R+
380	238	R-
385	0	F+
385	0	F-
385	2295	R+
385	181	R-
390	0	F+
390	0	F-
390	2203	R+
390	184	R-
395	0	F+
395	0	F-
395	2053	R+
395	188	R-
400	0	F+
400	0	F-
400	2071	R+
400	170	R-
405	0	F+
405	0	F-
405	2035	R+
405	125	R-
410	0	F+
410	0	F-
410	1952	R+
410	111	R-
415	0	F+
415	0	F-
415	1983	R+
415	74	R-
420	0	F+
420	0	F-
420	1851	R+
420	34	R-
425	0	F+
425	0	F-
425	1833	R+
425	8	R-
430	0	F+
430	0	F-
430	1717	R+
430	10	R-
435	0	F+
435	0	F-
435	1773	R+
435	4	R-
440	0	F+
440	0	F-
440	1679	R+
440	1	R-
445	0	F+
445	0	F-
445	1610	R+
445	6	R-
450	0	F+
450	0	F-
450	1536	R+
450	1	R-
455	0	F+
455	0	F-
455	1550	R+
455	5	R-
460	0	F+
460	0	F-
460	1485	R+
460	4	R-
465	0	F+
465	0	F-
465	1434	R+
465	3	R-
470	0	F+
470	0	F-
470	1424	R+
470	3	R-
475	0	F+
475	0	F-
475	1337	R+
475	2	R-
480	0	F+
480	0	F-
480	1283	R+
480	2	R-
485	0	F+
485	0	F-
485	1267	R+
485	1	R-
490	0	F+
490	0	F-
490	1246	R+
490	3	R-
495	0	F+
495	0	F-
495	1209	R+
495	0	R-
500	0	F+
500	0	F-
500	1161	R+
500	1	R-
505	0	F+
505	0	F-
505	1190	R+
505	4	R-
510	0	F+
510	0	F-
510	1126	R+
510	0	R-
515	0	F+
515	0	F-
515	1047	R+
515	3	R-
520	0	F+
520	0	F-
520	1065	R+
520	0	R-
525	0	F+
525	0	F-
525	1047	R+
525	2	R-
530	0	F+
530	0	F-
530	959	R+
530	1	R-
535	0	F+
535	0	F-
535	929	R+
535	2	R-
540	0	F+
540	0	F-
540	908	R+
540	1	R-
545	0	F+
545	0	F-
545	865	R+
545	0	R-
550	0	F+
550	0	F-
550	929	R+
550	3	R-
555	0	F+
555	0	F-
555	846	R+
555	0	R-
560	0	F+
560	0	F-
560	792	R+
560	0	R-
565	0	F+
565	0	F-
565	753	R+
565	0	R-
570	0	F+
570	0	F-
570	777	R+
570	2	R-
575	0	F+
575	0	F-
575	757	R+
575	0	R-
580	0	F+
580	0	F-
580	724	R+
580	0	R-
585	0	F+
585	0	F-
585	680	R+
585	0	R-
590	0	F+
590	0	F-
590	631	R+
590	0	R-
595	0	F+
595	0	F-
595	615	R+
595	0	R-
600	0	F+
600	0	F-
600	653	R+
600	0	R-
605	0	F+
605	0	F-
605	589	R+
605	0	R-
610	0	F+
610	0	F-
610	511	R+
610	0	R-
615	0	F+
615	0	F-
615	563	R+
615	0	R-
620	0	F+
620	0	F-
620	560	R+
620	0	R-
625	0	F+
625	0	F-
625	531	R+
625	0	R-
630	0	F+
630	0	F-
630	483	R+
630	0	R-
635	0	F+
635	0	F-
635	519	R+
635	0	R-
640	0	F+
640	0	F-
640	475	R+
640	0	R-
645	0	F+
645	0	F-
645	456	R+
645	0	R-
650	0	F+
650	0	F-
650	446	R+
650	0	R-
655	0	F+
655	0	F-
655	437	R+
655	0	R-
660	0	F+
660	0	F-
660	447	R+
660	0	R-
665	0	F+
665	0	F-
665	428	R+
665	0	R-
670	0	F+
670	0	F-
670	366	R+
670	0	R-
675	0	F+
675	0	F-
675	361	R+
675	0	R-
680	0	F+
680	0	F-
680	347	R+
680	0	R-
685	0	F+
685	0	F-
685	299	R+
685	0	R-
690	0	F+
690	0	F-
690	314	R+
690	0	R-
695	0	F+
695	0	F-
695	309	R+
695	0	R-
700	0	F+
700	0	F-
700	297	R+
700	1	R-
705	0	F+
705	0	F-
705	267	R+
705	0	R-
710	0	F+
710	0	F-
710	263	R+
710	1	R-
715	0	F+
715	0	F-
715	243	R+
715	1	R-
720	0	F+
720	0	F-
720	276	R+
720	0	R-
725	0	F+
725	0	F-
725	259	R+
725	0	R-
730	0	F+
730	0	F-
730	261	R+
730	0	R-
735	0	F+
735	0	F-
735	230	R+
735	0	R-
740	0	F+
740	0	F-
740	231	R+
740	0	R-
745	0	F+
745	0	F-
745	225	R+
745	0	R-
750	0	F+
750	0	F-
750	167	R+
750	0	R-
755	0	F+
755	0	F-
755	217	R+
755	0	R-
760	0	F+
760	0	F-
760	163	R+
760	0	R-
765	0	F+
765	0	F-
765	173	R+
765	0	R-
770	0	F+
770	0	F-
770	166	R+
770	0	R-
775	0	F+
775	0	F-
775	159	R+
775	0	R-
780	0	F+
780	0	F-
780	166	R+
780	0	R-
785	0	F+
785	0	F-
785	142	R+
785	0	R-
790	0	F+
790	0	F-
790	144	R+
790	0	R-
795	0	F+
795	0	F-
795	160	R+
795	0	R-
800	0	F+
800	0	F-
800	145	R+
800	0	R-
805	0	F+
805	0	F-
805	145	R+
805	0	R-
810	0	F+
810	0	F-
810	127	R+
810	0	R-
815	0	F+
815	0	F-
815	138	R+
815	0	R-
820	0	F+
820	0	F-
820	123	R+
820	0	R-
825	0	F+
825	0	F-
825	117	R+
825	0	R-
830	0	F+
830	0	F-
830	106	R+
830	0	R-
835	0	F+
835	0	F-
835	97	R+
835	0	R-
840	0	F+
840	0	F-
840	103	R+
840	0	R-
845	0	F+
845	0	F-
845	90	R+
845	0	R-
850	0	F+
850	0	F-
850	81	R+
850	0	R-
855	0	F+
855	0	F-
855	94	R+
855	0	R-
860	0	F+
860	0	F-
860	83	R+
860	0	R-
865	0	F+
865	0	F-
865	13	R+
865	0	R-

**Comment by tobiasrausch** [comment]
You have a mean read length of 172 and an average insert size of 206 so most read pairs will be overlapping and thus, you have greatly reduced power to detect SVs using paired-end mapping.

-Tobias

**Comment by yosr1977** [comment]
so what do you suggest ?
y
