### ISSUE TITLE
#include-ing htslib headers

### ISSUE THREAD

**Issue by jmarshall** [tobiasrausch/delly#20]
HTSlib's headers and installation scripts are set up so that the public headers are all installed into an `htslib` subdirectory of your include directory.  The intention is that source code should say e.g.

```c
#include "htslib/kseq.h"
```

and then if HTSlib headers are installed in `/usr/include/htslib/kseq.h` you won't need any -I or -isystem compiler options at all.

It would be easier to build delly against an already-installed HTSlib if delly followed this convention too.  This would just mean changing the makefile to point to HTSlib's top-level root:

```diff
diff --git a/Makefile b/Makefile
-SEQTK_ROOT    = ${PWD}/src/htslib/htslib
+SEQTK_ROOT    = ${PWD}/src/htslib
```

and changing src/extract.h and src/junction.h to `#include "htslib/kseq.h"` instead.

----

Alternatively, if `kseq.h` is the only part of HTSlib that you plan to use, I would suggest just copying `kseq.h` from its original [attractivechaos/klib](https://github.com/attractivechaos/klib) into the delly source tree (this is how **klib** is designed to be used) and avoiding the HTSlib dependency entirely.

**Comment by tobiasrausch** [comment]
Thanks for pointing this out John. I just replaced the bamtools API with the htslib API and changed the includes along the way. Should be fine now.
-Tobias

**Comment by jmarshall** [comment]
Excellent, thanks!  The htslib API is happy to have another user :smile:
