### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by svkazakov** [tobiasrausch/delly#22]
Hi

I got segmentation fault with the latest delly v0.6.6 (delly_v0.6.6_linux_x86_64bit):
./delly -t DEL -o del.vcf -g hg19.fasta tmp.sorted.bam 
[2015-Jul-07 16:57:39] ./delly -t DEL -o del.vcf -g hg19.fasta tmp.sorted.bam 
[2015-Jul-07 16:57:39] Paired-end clustering

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**zsh: segmentation fault (core dumped)  ./delly -t DEL -o del.vcf -g hg19.fasta 

File tmp.sorted.bam can be downloaded from:
http://rain.ifmo.ru/~svkazakov/files/tmp.sorted.bam

OS:
Linux 3.13.0-43-generic, Ubuntu 14.04, 64-bit

Sergey.

**Comment by tobiasrausch** [comment]
You just lack an index file.

samtools index tmp.sorted.bam
./delly -t DEL -o del.vcf -g hg19.fasta tmp.sorted.bam 

-Tobias

**Comment by svkazakov** [comment]
yes, it works now.
Thank you.

**Comment by svkazakov** [comment]
Also, can you, please, add some kind of message for that case?

**Comment by tobiasrausch** [comment]
I think, there is an error message if you compile Delly from source with a shared library but apparently it's gone in the static binary.

**Comment by svkazakov** [comment]
I have build Delly from source (before adding the issue) and run it on the same file and do not find any message.
