### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by martenj** [tobiasrausch/delly#28]
Hi,

running DELLY (Version: 0.6.7) with a set of about 25samples all I get is an Error.

command: delly -t DEL -g hs37d5.fa -o delly_DEL_sv.vcf -x human.hg19.excl.tsv 1.bam 2.bam 3.bam .... 25.bam

[2015-Sep-07 15:19:17] Paired-end clustering

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*Segmentation fault

Is it possible to get a more verbose error message or do you maybe know possible reasons? I've run the same command with even more samples and all went well.

Thanks.
Marten

**Comment by tobiasrausch** [comment]
Are all bam files sorted and indexed?

-Tobias
