### ISSUE TITLE
Question:  how to run the delly_parallel version

### ISSUE THREAD

**Issue by mxqian** [tobiasrausch/delly#30]
Hi,
Originally, I thought it should be run like this:
export OMP_NUM_THREADS=3
mpirun -n 3  $path/delly_parallel -t ...

Note:  this will use 3 processes and each process has multiple threads (dynamic).  I'm not sure the processes were duplicated or real in parallel

or just like this:
export OMP_NUM_THREADS=3
$path/delly_parallel -t ...

I'm confused.  Many thanks in advance.

**Comment by tobiasrausch** [comment]
Delly has no mpi support, it's just multi-threaded.

export OMP_NUM_THREADS=3
./delly_parallel -t ...

Best, Tobias

**Comment by mxqian** [comment]
OK, got it.  Many thanks. BTW,  the introduction about Open MPI in README has a little misleading. Maybe you can add a little more detail about this.
