### ISSUE TITLE
delly_v0.7.1

### ISSUE THREAD

**Issue by SSunkara** [tobiasrausch/delly#31]
Hi Tobias,

Have you mandated the split read analysis option -g with this release of delly?
I don't seem to be able to run delly otherwise?

Thanks,
Sirisha

**Comment by SSunkara** [comment]
Hi Tobias,

Also, could you comment on the graph pruning cut-off that is set at a default of a 1000...

Thanks again,
Sirisha

**Comment by tobiasrausch** [comment]
Yes, -g is now required because for small InDel discovery Delly re-aligns the reads to the reference.

-Tobias

**Comment by tobiasrausch** [comment]
For the graph pruning cutoff (default 1000): This sets the upper bound for how many paired-ends are at most collected for SV discovery at a given loci in the genome.

-Tobias

**Comment by tobiasrausch** [comment]
Hi Sirisha,

You may want to post Delly usage questions in the delly-users mailing list:

https://groups.google.com/forum/#!forum/delly-users

For actual bug reports, github issues is best, I think.

-Tobias
