### ISSUE TITLE
Delly 0.7.1 source .zip and .tar.gz files are missing dependencies 

### ISSUE THREAD

**Issue by pdblood** [tobiasrausch/delly#32]
Source files here: https://github.com/tobiasrausch/delly/releases/ are missing dependencies. For example, src/htslib directory is empty, causing "make all" to fail.  Not a big deal as I can pull from github.  Just FYI.

**Comment by tobiasrausch** [comment]
Including submodules within a GitHub source code release is currently not possible:

http://stackoverflow.com/questions/12936014/include-a-github-submodule-automatically-in-download

If you want a source code release (and not the static binaries) then a recursive clone with a git checkout of the required version tag is probably the easiest.
