### ISSUE TITLE
Delly run time for large WGS file

### ISSUE THREAD

**Issue by gerrybio** [tobiasrausch/delly#36]
Many thanks for such a great SV tool combining split-read and paired-end discordancy signals!

I'd like to look for SV for 20 WGS of patient samples of complex disease plus some controls from 1000 genome project.
Each patient sample has size around 70-80GB; and control smaller around 20GB

I'm wondering what's the run time cost of such bam file? I've done small test seems it runs relatively slow. To set -t INV/DEL/DUP to run separately? Or any possible way to run each chromosome separately?
Also, any possibility to run 20 WGS +20 control together? (That'll be cost lots of memory and super slow?) Or should I run each sample independently?

Hope to hear any suggestion for running Delly for multiple big WGS bam file

Many thanks!

**Comment by tobiasrausch** [comment]
You can run the chromosomes separately but we rarely do this. We usually run samples one by one or for matched tumor/normal samples we run the tumor and normal bam file together. We have used Delly in projects with several thousands of samples and the workflow for scaling up to N samples is:

(1) Run Delly sample by sample or in small batches
(2) Merge individual Delly VCFs called in (1) using:

./delly/src/merge –t DEL –m 500 –n 1000000 –o delly.DEL.sites.vcf.gz –b 250 –r 0.8 <sample1.vcf.gz> <sample2.vcf.gz> … <sampleN.vcf.gz>

(3) Re-genotype this site list across all samples

./delly/src/delly -t DEL -g <ref.fa> -v delly.DEL.sites.vcf.gz -o <output.sampleK.vcf.gz> -x ./delly/excludeTemplates/human.hg19.excl.tsv <sampleK.bam>

(4) Concatenate all re-genotyped samples to get a single VCF (bcftools merge) and then filter using Delly’s python scripts

Best, Tobias

**Comment by gerrybio** [comment]
Many thanks Tobias for your reply.

1. I know DELLY is used in 1000 genome project, that's why I chose DELLY. :)

2. I've run DELLY for deletion like below
`/delly -g /g1k_37.fasta -t DEL -x human.hg19.excl.tsv patient_rmdup.bam control.bam -o test.del.vcf.gz`
I request 4 cores each 2GB memory.
The patient bam is 70GB, control bam is 20GB
But I've waited a whole day, still I got NO output, and in std_output I got
```
[2016-Feb-24 15:00:33] Paired-end clustering

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
******
```
So DELLY is still clustering pair-end because bam file is too big?
I just don't know if I've done anything wrong or stupid so that the run won't go correct.

Thanks!

**Comment by tobiasrausch** [comment]
Delly recently started calling small InDels and this is not heavily optimized yet. You may just want to use '-n' which deactivates small InDel calling and uses the "old" Delly with paired-ends and split-read refinement.

Best, Tobias

**Comment by fpbarthel** [comment]
Hi @tobiasrausch, my delly analyses on 30x tumor-normal WGS bam files are also suffering from very long run times. I am using the following command to run delly:

```
delly call -n -x human_g1k_v37_decoy_svmask_delly.bed -o out.bcf -g human_g1k_v37_decoy.fasta tumor.bam normal.bam 
```

More than half (of ~20) tumor/normal pairs ran out of walltime (72 hours) using 2 cores and 12 GB of memory (without the `-n` parameter). I have now re-started all processes (with the `-n` parameter) and so far (24h later) only one is finished so far. My exclude bed file has 441 regions (including full mask for any extra contigs). Any other suggestions? What wall time is normal for 30x whole genomes?
