### ISSUE TITLE
Use local read-depth to further filter Delly results

### ISSUE THREAD

**Issue by gerrybio** [tobiasrausch/delly#39]
Hi 
I know Delly is based on read-pair and split-read, but I'm wondering any auxiliary package for local read-depth check for the callings in order for further filter? 

I read from supplementary document of 1000Genome Project:
"Read-depth (RD) of all candidate deletions was annotated using ‘cov’, an auxiliary tool from the	Delly package.	The	raw read-depth values...."

Obviously there's some read-depth filter package, but I'm wondering where I could find from Delly software? THX!

**Comment by tobiasrausch** [comment]
Delly is indeed using read-depth to filter SVs in a cohort of WGS samples. Delly's filter program is implementing this read-depth approach. Just follow the germline SV calling workflow outlined in the README:

https://github.com/tobiasrausch/delly/blob/master/README.md

Please post any further usage/installation questions to the delly-users mailing list.

Thanks, Tobias

**Comment by gerrybio** [comment]
Thanks I see. 
But a silly question: I don't find any "filter" under "delly/src" ?

**Comment by gerrybio** [comment]
Thanks. But before moving to delly-users, one question:
I see the "filter" option in Delly2 documentary:
`filter -t DEL -f germline -o germline.bcf -g hg19.fa merged.bcf`
But I don't find any `filter` under delly/src/

Also in README.md I saw
Copy-number variable polymorphic SV sites:

`python cnvClassifier.py -v del.vcf -o del.sites.vcf -f`


I'm very confused now how I should do read-depth filter

Thanks

**Comment by tobiasrausch** [comment]
I added the compiled filter program some time last week. 

https://github.com/tobiasrausch/delly/blob/master/src/filter.cpp

It will soon replace the old python script. You need the latest delly github code and then

make src/filter

should build the program. I will also release a new delly version rather soon but some tests are still running.
