### ISSUE TITLE
Algorithm of read-depth filter function in Delly

### ISSUE THREAD

**Issue by biomedicineman** [tobiasrausch/delly#40]
I have a couple of question about the newly-added filter function for germline SV in Delly.

1. What's the algorithm for RD filter?  (Gaussian	Mixture	Model	was	applied to	model	the	read-depth	distribution	and	assign	copy number	states? This is what I found from 1000Genome Project supplementary). 
And what information you are retrieving? Seems filter function only relies on vcf output file, NOT bam; so you must retrieve information only from vcf file

2. The filter is conducted sample by sample? I mean filtering for patient A is independent from patient B, if I called SV for two patients within one vcf file?

3. For my sample, the raw Delly-deletion gave me 7000 calls, but after "filter", only 400 are remained. Is that normal?

4. If I think the filtering is too stringent, what parameters would you recommend to tweak? And I found:
-e [ --rddel ] arg (=0.800000012)     max. read-depth ratio of carrier vs. non-carrier for a deletion

Could you please explain a little bit what's "carrier" and "non-carrier" here?

Many many thanks!

**Comment by tobiasrausch** [comment]
Please do not double-post questions on github and the delly user group. I try to respond as quickly as possible. The answer to your question is here:

https://groups.google.com/forum/#!topic/delly-users/44_6F5pa9bI

Thanks, Tobias
