### ISSUE TITLE
Confusing about CT

### ISSUE THREAD

**Issue by yuanyuanji** [tobiasrausch/delly#41]
#INFO=<ID=CT,Number=1,Type=String,Description="Paired-end signature induced connection type">

I am using delly, however I am confusing about the argument ‘CT’---3to3,3to5,5to3,5to5

I have read the reference and I know that it is about in order&invert， However I also confuse about that.

can anyone give  me a specific concept about these 4 types？（where the 2 reads aligned？ the orientation of the reads？ if we determined the 3 relevant breakpoints in reference sequence as From_start、From_end（=From_start+length）、To， which two breakpoints is corresponding to which type？ ）

Thanks

**Comment by tobiasrausch** [comment]
There was some information exchange on this in the Delly users group:

https://groups.google.com/forum/#!topic/delly-users/6Mq2juBraRY
