### ISSUE TITLE
Naming of output files

### ISSUE THREAD

**Issue by meiers** [tobiasrausch/delly#42]
Hi Tobi,

any particular reason why you remove the suffix of the filename twice, [for example here](https://github.com/tobiasrausch/delly/blob/master/src/merge.h#L669)?
Because that leads to the situation that output files get overwritten when I run
```
delly merge -t INV -o merge.INV.bcf a.bcf a.bcf
delly merge -t TRA -o merge.TRA.bcf a.bcf a.bcf
````
Thanks

**Comment by tobiasrausch** [comment]
Thanks. Delly is using now temporary files to merge the different CTs. These temporary files are then merged together into a final BCF. Should be fine now.

-Tobias
