### ISSUE TITLE
BCF output samplename

### ISSUE THREAD

**Issue by wyleung** [tobiasrausch/delly#44]
I'm using version:

`delly_v0.7.3_linux_x86_64bit`

The samplename reported in the BCF/VCF is based on the filename of the inputBAM. This is not the desired name. I'd expect the sample name would be derived from:

` @RG     ID:70001-5 PU:na   LB:9834643      SM:700014 PL:illumina`

The `SM` field?

**Comment by wyleung** [comment]
I think it is related to here:

https://github.com/tobiasrausch/delly/blob/3b6f3ab3bbcadb9c862f90ebc02fa0de139f7a1c/src/delly.h#L454

**Comment by tobiasrausch** [comment]
It's true the sample name is derived from the input bam file name. The problem with the SM tag is that a single BAM file can have multiple SM tags and Delly is not yet taken care of this.

**Comment by wyleung** [comment]
Is this something which will be on your development for the next release?

**Comment by tobiasrausch** [comment]
Yes, I will use the SM tag in the next version and if it is not present fall back to the filename.

**Comment by tobiasrausch** [comment]
Just committed some code that now uses @RG:SM so this should be fixed.
