### ISSUE TITLE
dockerfile problem version chardet==2.0.1

### ISSUE THREAD

**Issue by sphilippot** [tobiasrausch/delly#46]
hello,
When use the dockerfile, i have an error with  pip install chardet==2.0.1 in  delly/complexVariants/requirements.txt.
pip can't find this version:

" Could not find a version that satisfies the requirement chardet==2.0.1 (from -r delly/complexVariants/requirements.txt (line 3)) (from versions: 1.0, 1.0.1, 1.1, 2.1.1, 2.2.1, 2.3.0)
No matching distribution found for chardet==2.0.1 (from -r delly/complexVariants/requirements.txt (line 3))
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command."

I am trying to use another version of chardet as 2.1.1 but i have another error. 
perhaps upgrading pip ?

**Comment by tobiasrausch** [comment]
Thanks, added your patch.

FROM ubuntu:14.04

Best, Tobias
