### ISSUE TITLE
Confusion about merge output of different SV types (DEL/DUP/INV/TRA/INS)

### ISSUE THREAD

**Issue by CllKiller** [tobiasrausch/delly#50]
Hi, Tobias. Thanks for such a methodical software for SV calling!

Recently, I had tried Delly (delly_v0.7.3_linux_x86_64bit) to call several different types of SV (DEL/DUP/INV/TRA/INS) from my WGS data in the Germline SV Calling mode, here is the command I used to call DEL :

$delly merge -t DEL -m 0 -n 1000000 -o MAGIC.DEL1.bcf -b 1000 -r 0.8 IND1.bcf IND2.bcf IND3.bcf IND4.bcf IND5.bcf IND6.bcf IND7.bcf IND8.bcf IND9.bcf IND10.bcf 

And then I generate a DEL site list (MAGIC.DEL1.bcf and MAGIC.DEL1.bcf.csi). The merge output files are similar when I call DEL, DUP and INS, but when I turn to merge INV and TRA, I got more files:
INV: MAGIC.3to3.bcf and MAGIC.5to5.bcf
TRA: MAGIC.3to3.bcf, MAGIC.3to5.bcf, MAGIC.5to3.bcf and MAGIC.5to5.bcf

Q1: Could you please explain me a bit more about these files above?
Q2: As for DEL, I can just use this command to re-genotype merged DEL site list like:
$delly call -t DEL -g MAGIC.fa -v MAGIC.DEL1.bcf -o Ind1.geno.bcf -x MT_CP.excl Ind.bcf
But for INV and TRA, how could I re-genotype with the list files above?

Best,
Leilei

**Comment by tobiasrausch** [comment]
This was discussed recently on the delly-users mailing list:

https://groups.google.com/forum/#!topic/delly-users/kogw78-hqoc
