### ISSUE TITLE
Error with Sauve visualization

### ISSUE THREAD

**Issue by dtm2117** [tobiasrausch/delly#51]
I'm having this error when trying to run Suave on paired WES samples. I ran delly to locate translocations, and converted the .bcf to .vcf. Here is the output: 

10.7.203.62 - - [14/Jul/2016 13:03:09] "GET / HTTP/1.1" 200 -
10.7.203.62 - - [14/Jul/2016 13:03:09] "GET /static/googlefonts/stylesheet.css HTTP/1.1" 304 -
10.7.203.62 - - [14/Jul/2016 13:03:09] "GET /static/suave.css HTTP/1.1" 304 -
10.7.203.62 - - [14/Jul/2016 13:03:09] "GET /static/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 -
10.7.203.62 - - [14/Jul/2016 13:03:09] "GET /static/jquery.min.js HTTP/1.1" 304 -
10.7.203.62 - - [14/Jul/2016 13:03:09] "GET /static/font-awesome/css/font-awesome.min.css HTTP/1.1" 304 -
10.7.203.62 - - [14/Jul/2016 13:03:09] "GET /static/d3.min.js HTTP/1.1" 304 -
10.7.203.62 - - [14/Jul/2016 13:03:09] "GET /static/bootstrap/js/bootstrap.min.js HTTP/1.1" 304 -
10.7.203.62 - - [14/Jul/2016 13:03:09] "GET /static/underscore-min.js HTTP/1.1" 304 -
10.7.203.62 - - [14/Jul/2016 13:03:09] "GET /static/typeahead.js/typeahead.bundle.min.js HTTP/1.1" 304 -
10.7.203.62 - - [14/Jul/2016 13:03:09] "GET /static/suave.js HTTP/1.1" 304 -
10.7.203.62 - - [14/Jul/2016 13:03:09] "GET /static/bootstrap/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 304 -
10.7.203.62 - - [14/Jul/2016 13:03:09] "GET /static/font-awesome/fonts/fontawesome-webfont.woff2?v=4.3.0 HTTP/1.1" 304 -
10.7.203.62 - - [14/Jul/2016 13:03:16] "GET /chroms/GB1_tumor/control HTTP/1.1" 200 -
1 249250621 10000 0 2492506
suave_server.py:149: RuntimeWarning: invalid value encountered in true_divide
  for r in np.log2(x_sum / y_sum / cfg['norm'])
suave_server.py:149: RuntimeWarning: divide by zero encountered in log2
  for r in np.log2(x_sum / y_sum / cfg['norm'])
10.7.203.62 - - [14/Jul/2016 13:03:18] "GET /depth/GB1_tumor/control/1?n=10000 HTTP/1.1" 200 -
index `/home/dmelnekoff/Delly_Output/GB1_test.vcf.gz.tbi` not found
10.7.203.62 - - [14/Jul/2016 13:03:18] "GET /calls/1 HTTP/1.1" 500 -

Do I need to generate a .tbi file from my Delly generated .vcf for this to work? 

Thanks

**Comment by meiers** [comment]
Hey,
just out of curiosity, what was the issue? We are always happy to get some user feedback.
Best,
Sascha

**Comment by dtm2117** [comment]
In the end I did need to generate a .tbi file for my delly generated .vcf using tabix.
