### ISSUE TITLE
Question on Delly's Inversion detection 

### ISSUE THREAD

**Issue by odoland** [tobiasrausch/delly#52]
Hello Delly developers,

I am trying to detect if there are any large inversions (around 1 mbp to 10 mbp) that may have resulted from large deletions. I am relatively new to command-line usage. So far, I have tried other SV prediction software such as pindel, lumpy and sv-detect, but they have only detected inversions of less than 200 bp. I am not sure if it is because of the Alignment or SV-prediction softwares.

Our mate-pair library has mean insert size of around 2,000 - 3000 bp, and I am attempting to detect a very large inversion ( 2,000,000 bp +).  

My question is, would Delly be able to detect an inversion that large?
I am not sure if split-read analysis would be able to predict such a large inversion, or if the algorithm would work well with larger insert sizes.

Thanks!

**Comment by tobiasrausch** [comment]
Delly should be fine for this if the mate-pair insert size distribution is approximately normal. 

https://github.com/tobiasrausch/delly/wiki/Alignment-Statistics

If you have further delly usage questions please consider using the mailing list: 

http://groups.google.com/d/forum/delly-users

Thanks, Tobias
