### ISSUE TITLE
Translocation file doesn't have anything for chr1

### ISSUE THREAD

**Issue by ccsstudentmentors** [tobiasrausch/delly#53]
I have ran the delly translocation analysis and for some reason nothing is showing up on chr1.  Every other chromosome has at least some low quality or pass results, but nothing is showing up for chromosome 1.  Chromosome 1 results are showing up for the deletion, duplication, and inversion analysis.  Is this a bug?

**Comment by tobiasrausch** [comment]
Delly is streaming the BAMs and since translocations are inter-chromosomal the first calls occur at chr2. You will find a lot of calls with INFO:CHR2=chr1.
