### ISSUE TITLE
Trouble with somatic filtering

### ISSUE THREAD

**Issue by racheljones** [tobiasrausch/delly#54]
Hi Tobias,

I have run the delly call for del, dup, inv and tra. And I would now like to filter somatic variants.

This is my line of script
delly filter -t DEL -f somatic -o /data/240del.pre.bcf -s /data/samples.tsv -g /data/hg19.fa /data/240del.bcf

My samples.tsv file looks like this:
240control    control
240tumor      tumor

But I am getting an error message:
Sample type for 240_control is neither tumor nor control

Are you please able to advise how I could fix this?

Thanks,
Rachel

**Comment by tobiasrausch** [comment]
Hi Rachel,

According to the delly error message your sample sheet lacks an underscore, '240_control' instead of '240control'.

Best, Tobias

**Comment by racheljones** [comment]
Thanks. I still have the same problem when I have
240_tumor          tumor
240_control        control


In the sample.tsv file



Rachel Jones
PhD Candidate I Centre for Genetic Origins of Health and Disease
Faculty of Medicine, Dentistry & Health Sciences, The University of Western Australia
Level 5 MRF Building 50 Murray Street, Perth WA
Tel: +61 8 9224 0394

**Comment by tobiasrausch** [comment]
The sample.tsv file looks fine. Are you using the latest bcftools version or the one shipped with Delly in ./src/bcftools/bcftools ? It could also be that you have very low tumor content then you could try this:

delly filter -t DEL -f somatic -o /data/240del.pre.bcf -s /data/samples.tsv -g /data/hg19.fa -m 0 -a 0.05 -r 0.1 /data/240del.bcf

**Comment by ghzhaole** [comment]
I met the same problem with you and I found out that my sample.tsv file was edited in Windows (CRLF) format. And the problem was solved when I transformed it into Unix (LF) format.
