### ISSUE TITLE
Visualising Delly output + Fusion detection

### ISSUE THREAD

**Issue by mortunco** [tobiasrausch/delly#56]
Hi,

Thank you for processing ICGC data. I have obtained about ~250 patient vcfs from ICGC and I would to call a specific fusion based on delly output caused by a translocation. 

1)What should be the best method for this kind of querry?
—> I thought visualising and deciding by my eye. This raised visualisation problem. Neither bedpe output nor vcf output helped out with the visualisation. (IGV and other genome browsers works but its really hard to asses translocation so I wanted to draw a circos plot.)

2) I have read about using snpEff or VEP(I am not sure about this). But as far as I know, snpEff does not support translocations so it won't work for my case.

3) Lastly, forgive my ignorance about the following terminology. Bedpe and reedname. Could you give me at least a source about this two file extensions ? (For example what is the difference btw bedpe and vcf. I know what is bed file but I couldnt link these together in structural variation subject.)

Sorry for asking bunch of questions. My graduate project is based on this data therefore, I am trying to process this information as good as possible.

Thank you for your patience,

Best,

Tunc/.

**Comment by tobiasrausch** [comment]
Hi,

To visualize inter-chromosomal translocations I first create a BED file where I split the 2 breakpoints of a given translocation into 2 lines and then add +/-500bp to look at the breakpoints in IGV. The tool I use for that is svprops (https://github.com/tobiasrausch/svprops).

svprops tranlocation.bcf | cut -f 1-5 | awk '{print $1"\t"($2-500)"\t"($2+500)"\t"$5"Left\n"$3"\t"($4-500)"\t"($4+500)"\t"$5"Right";}' > breakpoints.bed

IGV has a region navigator that allows to import BED files then it is very easy to iterate through all Delly translocation calls (http://software.broadinstitute.org/software/igv/regionsofinterest).

You should also switch on the paired-end view as illustrated in the Delly tutorial (https://www.gitbook.com/book/tobiasrausch/tutorial-delly/details) or here in the IGV help (http://software.broadinstitute.org/software/igv/AlignmentData#paired). The split screen view of IGV can also be helpful occasionally. 

Please consider using the delly-users mailing list for these kind of questions.

https://groups.google.com/forum/#!forum/delly-users

Best, Tobias
