### ISSUE TITLE
Germline filtering gives no calls

### ISSUE THREAD

**Issue by woodoo46** [tobiasrausch/delly#57]
I used delly filter to filter calls, it turns out there is no call was output. This is the command I used:

delly filter -t DEL -f germline -o a.bcf -g hg.fa rawcalls.bcf

There are calls in the rawcalls.bcf. 

Any idea?  Thanks.

**Comment by tobiasrausch** [comment]
delly filter requires a VCF/BCF file of multiple samples (at least >=10) because it compares SV carriers with SV non-carriers. Do you have multiple samples in your input BCF file (rawcalls.bcf)?


-Tobias

**Comment by tobiasrausch** [comment]
Is this solved? If not please re-open.
